sudo: required
services:
- docker
jobs:
  include:
  - stage: ci-cd
    script: make build test
  - stage: release
    if: branch = master
    script: echo true
    deploy:
    - provider: rubygems
      skip_cleanup: true
      gem: docker_registry2
      api_key:
        secure: gK7HtgcW/6Kj9U5d3sgN9O90fThwr6QgSeBXCUUitoF7zW09K1DXKa1YazFe082XqxYa3ZLe+ocPEX/aXdxCMr0ZrxbpQT9MV7857W+xRkvTwg1RvITAHvU2EeH8rvYnpP7L8Akm6toTWp77jx+WRDaLQAaTwKWyFAAjQYLTYWOh8oU16qLGVn+XqjyDZKJfkVwuXJSF6d0vhs43rypVqFpsBDnXBS/g69yd0UGA1xwt+/LChcfz6I/HQp/MwedGjaadIm7So7a7hbZHpB3rnxOfh3YvWQeD7dtGiGFIEPszxCbSiOYlh2rjEBN76sLowl8Tb4J/qtsDTF/LpB84Kii6PIM3jpUr+NrdX3b8oG30NYnnMXuSBPmS1YacgywI8S7Ri61j9b4P8MbJNAMyjzvf4qYKEtKsht+uOzooRhFvMhBajRuBuJSXdzF1nv31ONc4Mmw8x1fU8z9pqEFFrmJ/sxdumkmGaTulFr1wFItYBfuhQdtBMJoa63jv7x2HBCdIXQWlyc0A2brdGKZAnLR1lqQWekJCiik7BuG/444yP7LeY/1as4emGYRsh3W504DZmtC+ou4D0vI2IVSi9ebZu6DDforJBOZNXOEOi4J9UmGeGPkq04J+VvvgyfCqvDiTEy550qV9PKglCg0sEqa5SuTIrJVWjQpi24NZ8+E=

