# circleci to build and test; deploy when on master
---
version: 2.1
jobs:
  ci:
    docker:
      - image: circleci/ruby:2.4.2-jessie
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      # no need to install docker, as it is included in the above circleci/ruby image
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: CI
          command: make build test
  deploy:
    docker:
      - image: circleci/ruby:2.4.2-jessie
    steps:
      - attach_workspace:
          at: .
      - run:
          name: creds
          command: ./save-gem-creds.sh
      - run:
          name: push
          command: make push BUILD=local

workflows:
  version: 2
  test-deploy:
    jobs:
      - ci
      - deploy:
          requires:
          - ci
          filters:
            branches:
              only: master
