# circleci to build and test; deploy when on master
---
version: 2.1
jobs:
  ci:
    docker:
      - image: circleci/ruby:2.4.2-jessie
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - run:
          # this step is entirely because circleci does not support mounting volumes
          name: Install Docker client
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            chmod 0755 /tmp/docker/*
            mv /tmp/docker/* /usr/bin
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: CI
          command: make build test
  deploy:
    docker:
      - image: circleci/ruby:2.4.2-jessie
    steps:
      - run:
          name: push
          command: make push

workflows:
  version: 2
  test-deploy:
    jobs:
      - ci
      - deploy:
          requires:
          - ci
          filters:
            branches:
              only: master
